version: '3'

services:
  web-server:
    image: web-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/evo_exchange?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    command: mvn clean spring-boot:run
    depends_on:
      - database
    networks:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: evo_exchange
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge